### ISSUE TITLE
index.ts causes unused files to be marked as in use

### ISSUE THREAD

**Issue by gajus** [smeijer/unimported#107]
I have a project with the following structure:

```ts
src/utilities/stringToPath.ts
src/utilities/index.ts
src/bin/server.ts
```

`src/utilities/index.ts` simply re-exports utilities, e.g.

```ts
export { stringToPath } from './stringToPath';
export { parseUrl } from './parseUrl';
```

`src/bin/server.ts` imports one of the utilities from `src/utilities/index.ts`:

```ts
import { parseUrl } from '../utilities';
```

`stringToPath` is not imported by anything.

I would expect `stringToPath` to be reported as unimported, but it is not.

**Comment by smeijer** [comment]
This is out of the scope of unimported. We analyze the import paths, and your files are all imported. So the result is correct. By importing the file, it becomes used and the reexported functions become part of your public api. It's not up to unimported to see if your code is used or unused. We simply scan for dangling files. Not for dead or otherwise unused code.

**Comment by remy90** [comment]
This would be a really nice-to-have
