### ISSUE TITLE
unimported with re-exported variables

### ISSUE THREAD

**Issue by ecarlson2020** [smeijer/unimported#134]
Unimported has worked great for our project! Thank for all of the teams hard work. We've had one problem though. Say I have an unused file in my React project called `components/Hello.js`. Unimported will accurately report this file as unimported. However, say in my project I also have `components/index.js` with the following content:
```
export { default as Hello } from './components/Hello.js';
export { default as Hello2 } from './components/Hello2.js';
```
If anywhere in my project uses the code `import { Hello2 } from 'components'`, then unimported will no longer flag `components/Hello.js` as unimported because it occurs in `components/index.js`. Of course, after removing the first line from `components/index.js`, then unimported will work as expected, but in a large project with tons of these `index.js` files, it becomes tedious to do this. Is there a way to have unimported still work as expected even with these `index.js` files?

**Comment by smeijer** [comment]
Unfortunately, there is currently no way to detect that. I'm also not sure if it's worth adding support for that, as the files might be imported because of side effects.

There are tools for dead code detection. Unimported is meant to detect dangling files. The index.js imports the file, and thereby its no longer dangling.

I haven't tried it. But what you're looking for sounds like https://www.npmjs.com/package/ts-unused-exports.

**Comment by ecarlson2020** [comment]
> Unfortunately, there is currently no way to detect that. I'm also not sure if it's worth adding support for that, as the files might be imported because of side effects.
> 
> There are tools for dead code detection. Unimported is meant to detect dangling files. The index.js imports the file, and thereby its no longer dangling.
> 
> I haven't tried it. But what you're looking for sounds like https://www.npmjs.com/package/ts-unused-exports.

Awesome, thank you for your quick response. I will look into this further.
