### ISSUE TITLE
[Feature Request] CI (Github Actions) or Markdown compatible output

### ISSUE THREAD

**Issue by jonahallibone** [smeijer/unimported#143]
Hi!

This component has been great for me team and I cleaning and maintaining out repo, but I want to bring this library into our CI pipeline in a more visible way than just failures. Often, we don't want the actions to fail if we have unused files, but rather we just want to have to documented in the PR for visibility. Would you consider adding a feature or accepting a PR which introduced a flag like `--markdown-output` or `--actions-format` etc that would return without a failure code and returned a markdown version of the results?

Let me know if this is something you'd be interested in. I'd be more than happy to make the contribution for this as well.

**Comment by smeijer** [comment]
Hi, yes, I'd be very interested in additional formatters. Having a `--format markdown` or `--format json` would be a great feature.

I can see the value of not aborting actions when there are missing files. Eslint has `--exit-on-fatal-error` _("Exit with exit code 2 in case of fatal error - default: false")_. I guess we can do the same? Exit with code 2 if `--non-fatal` was provided?

Related: #106

**Comment by jonahallibone** [comment]
@smeijer Great. I can give it a shot if you want, or if you've already got some ideas on how to accomplish this I'd love to talk more about how this can be implemented

**Comment by smeijer** [comment]
Sweet, that'd be great!

So the printer is already extracted. The current one, can be found at https://github.com/smeijer/unimported/blob/2b590a66173dca18b6ccb9fa4b58ef6bfb75a1d7/src/print.ts. I think we can rename that one to `printer-console`, and then create a new `printer-markdown` and `printer-json`. Then we can create a new `printer.ts` that just delegates the call to one of those format specific printers. Something like:

```
import * as jsonPrinter from 'printer-json';
import * as markdownPrinter from 'printer-markdown';
import * as consolePrinter from 'printer-console';

function print(data, format) {
  if (format === 'json') return jsonPrinter.print(data);
  if (format === 'markdown') return markdownPrinter.print(data);
  return consolePrinter.print(data);
}
```

The printer is called at https://github.com/smeijer/unimported/blob/2b590a66173dca18b6ccb9fa4b58ef6bfb75a1d7/src/index.ts#L282 and https://github.com/smeijer/unimported/blob/2b590a66173dca18b6ccb9fa4b58ef6bfb75a1d7/src/index.ts#L273. I think we can make that call the new printer that will delegate the call to the format specific one.

--- 

**bonus:** If you feel for it, I also think we can refactor that part in `index.ts` a bit. The `results` object currently has the shape:

```ts
export interface ProcessedResult {
  unresolved: [string, string[]][];
  unimported: string[];
  unused: string[];
  clean: boolean;
}
```

I think ideally that should just be:

```ts
export interface ProcessedResult {
  unresolved: [string, string[]][];
  unimported: string[];
  unused: string[];
  removedDeps: string[];
  deletedFiles: string[];
  clean: boolean;
}
```

So we only have a single print function, instead of the current two. But again, that's bonus and not strictly needed to add the json / markdown parsers.

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
