### ISSUE TITLE
Support Vue

### ISSUE THREAD

**Issue by FlorianWendelborn** [smeijer/unimported#19]
I’m unfortunately stuck with a framework that encourages using non-standard `.vue` files. Would be amazing if `unimported` could parse them.

Should be rather easy to implement an MVP version IMO, as the most important part would basically be to just ignore everything outside of the `<script>` block (as that’s not JS/TS) and interpret the result as `(j|t)sx?`

---

```
yarn run v1.22.10
$ ./node_modules/.bin/unimported .
⠙ resolving imports
Failed parsing ./source/SomeVueFile.vue
{
  index: 34,
  lineNumber: 2,
  column: 23,
  message: 'Identifier expected.'
}
```

**Comment by smeijer** [comment]
Do you have an example project?

**Comment by FlorianWendelborn** [comment]
@smeijer here’s an official example of a vue.js project: <https://github.com/vuejs/vue-hackernews-2.0>

**Comment by wojtiku** [comment]
Vue support would be amazing! <3

**Comment by smeijer** [comment]
This should work now, albeit in a basic form.

I just strip the content from the `<script>...</script>` tag using string mutations (because I don't want to include a heavy html parser), and use that as the source. So there are some limitations. The most important one, both those tags need to stand on their own line! But I think that's a good convention to use anyways :sweat_smile: 

In other words. This works:

```vue
<template>...</template>
<script>
  ...
</script>
```

This does not:
```vue
<template>...</template>
<script>...</script>
```

I also only support a single `<script>` tag per `.vue` file, as vue [seems to have that limitation as well](https://github.com/vuejs/vue-loader/issues/228#issuecomment-231967919);

The example project also does something smart regarding two build targets and aliasing `create-api` to `create-api-client` or `create-api-server` depending on which build config is used. Note that this is something that unimported currently does not support.

To enable support for vue projects, add the `.vue` extension to your `.unimportedrc.json` config. For example, this is the config I used on the hackernews project:

```json
{
  "entry": ["src/entry-client.js", "src/entry-server.js"],
  "extensions": [".js", ".vue"],
  "aliases": {
    "create-api": ["./src/api/create-api-client"]
  }
}
```

Please let me know if this works for you.

**Comment by FlorianWendelborn** [comment]
I can confirm that vue support seems to be working (it no longer crashes) on a rather big project, so that’s a good start.

However, I’m not entirely sure if the results are as-expected or if there is some weirdness that may or may not be related to vue. I got **a lot** of false positives. The app in question has multiple entry points, and I have the suspicion that a file counts as "unimported" if it’s not imported by **all** entrypoints. Is that correct, or is there any possibility that this is related to vue?

If yes, is there any way to turn this off? I don’t think it’s helpful for detecting actually dead code, as with 4 entry points, nearly every file will be detected as dead.

**Comment by FlorianWendelborn** [comment]
I actually read the implementation and I have a pretty good idea of a possible cause. You’re strictly filtering for lines that equal `<script>`, however vue also supports some more lines like:

1. `<script lang="ts">` (heavily used in the code-base I’m talking about and by far the most relevant/easy/useful fix)
2. `<script src="./script.js"></script>` (IMO rarely used, would be fine for my usecase at least to ignore this) [link](https://vue-loader-v14.vuejs.org/en/start/spec.html)

**Comment by smeijer** [comment]
@FlorianWendelborn a file counts as unimported if it's not imported by at least one of the entry files. So that's not the issue.

I'll reopen the ticket to add support for the other vue script patterns as well. Thanks for diving into this.

**Comment by FlorianWendelborn** [comment]
@smeijer Just making sure you saw, I created an issue with a suggested patch in #51 via `patch-package`. With this patch, I successfully got `unimported` to work in @3YOURMIND’s CI pipeline

**Comment by smeijer** [comment]
The four entry files, is that common and by convention?

**Comment by FlorianWendelborn** [comment]
@smeijer the (private) app in question has 4 main entry points because it’s separated into 4 different web-apps for 4 different kinds of users. It’s not the case for most vue apps, but it is useful in this particular one.

**Comment by FlorianWendelborn** [comment]
@smeijer I pinged you on https://github.com/3YOURMIND/kotti/pull/475 as well, that’s a more typical use-case for `unimported` + `vue` IMO

**Comment by smeijer** [comment]
Should be fixed now :sunglasses: . Thanks for all the info.

**Comment by FlorianWendelborn** [comment]
@smeijer I can confirm that upgrading to 1.18.0 and removing the previous `patch-package` patch still works as expected. Thanks for the fix
