### ISSUE TITLE
support type imports for flow type

### ISSUE THREAD

**Issue by jhubble** [smeijer/unimported#38]
Our project uses flow, with some files just containing type definitions. These files are only references via a type import:
import type {MyType} from 'typefile'
unimported flags the the typefile as not imported.

**Comment by smeijer** [comment]
Typescript has the same syntax for type imports. I'm happy to merge a PR that adds this.

**Comment by smeijer** [comment]
It turns out that even though we do support this for typescript-based projects, we don't for flow type. For flow-based projects, we simply strip out all types before running the code through our parser. Which is done [here](https://github.com/smeijer/unimported/blob/6e5db89b00daa20bd61c952763fad9b766b1fd79/src/traverse.ts#L152) using the official [`flow-remove-types`](https://www.npmjs.com/package/flow-remove-types) package.

Thereby, the `type imports` simply don't exist at the moment we traverse the code. Making this a nontrivial feature request.

I've decided that I'm not going to spend (more) time on that, because I don't use flow, and this won't be something easy to do. I'm going to close this issue, but if someone is willing to dedicate time to it, and submit a pull request, I'm still happy to get it merged.

**Comment by smeijer** [comment]
Reopening, as I have an idea on how to fix this.

**Comment by smeijer** [comment]
This should be supported in `v1.19` :tada:
