### ISSUE TITLE
Allow to ignore patterns in ignoreUnused

### ISSUE THREAD

**Issue by gajus** [smeijer/unimported#62]
e.g. getting many false-positives for `@babel/` and `@types/`

```
   1 │ @babel/polyfill
   2 │ @react-stately/checkbox
   3 │ @testing-library/cypress
   4 │ @tsconfig/node12
   5 │ @types/express
   6 │ @types/gapi.auth2
   7 │ @types/http-terminator
   8 │ @types/ioredis
   9 │ @types/is-object
  10 │ @types/lightship
  11 │ @types/segment-analytics
  12 │ @types/ua-parser-js
  13 │ @types/yargs
```

Would like to just ignore `@babel/*` and `@types/*`.

**Comment by smeijer** [comment]
Can you create a repro? I think this might also cause your scan to be so slow. (#60).

**Comment by gajus** [comment]
Never mind. This solved the speed issue, but the underlying issue being discussed here remains (I accidentally excluded those files in the config).

Debugging further.

**Comment by smeijer** [comment]
That might be worth adding to the readme.

**Comment by jarjee** [comment]
Hi, just chiming in with a different use case which could benefit from patterns in `ignoreUnused`.

We're using webpack with `url-loader`, which means that in our source code we have imports like the following:

```typescript
import FirstIcon from 'svg/example-icons/first.svg';
import SecondIcon from 'svg/example-icons/second.svg';
import ThirdIcon from 'svg/example-icons/third.svg';
```

This then leads to a whole bunch of unresolved imports where I have to specify every single svg/gif asset that should be ignored. Not impossible, it just makes the `.unimportedrc.json` file pretty large.

I guess a more "future-proof" solution is something like #57, where you can check for assets as well as code, but letting you apply patterns in `ignoreUnused` is probably easier.

**Comment by smeijer** [comment]
So, just a few options that come to mind that we can add to support this use case:

1. Add the ignore patterns. Again, I'm not a big fan of that as it makes it very easy to get false negatives, but I'm willing to accept a PR if that's really what you want/need.
2. Add support for assets. File paths/patterns that are recognized as such, and flagged as used, but not read & parsed. This would probably require something like `assetPatterns`, to declare which patterns should be handled as such. Think `assetPatterns: ['/svg/**/*.svg']`, but also `assetFolders`, to specify which folders should be scanned so there is something to flag as "unimported".

I'm happy to hear other suggestions/thoughts so that we can add support for this in the best way possible.

Also, contributions (pull requests) would be immensely appreciated. I'm in a big lack of time at this moment due to personal/family reasons. I'm happy to chat and share my thoughts, I don't think I have time to contribute code to this subject in the upcoming weeks.

**Comment by jarjee** [comment]
I honestly like `2` more, maybe something like:

```json
{
  "assetExtensions": [".svg", ".gif"],
  "assetFolders": ["src/assets", "ios/src/example"],
  (or/and)
  "assetRoot": "src/assets"
}
``` 
Although I'm wondering how this would work with `alias` and `rootDir`.

`2` arguably opens the pandoras box of alternate loaders:

```json
{ 
  "loaders":  {
     "assets": { ... },
     "sass": { ... },
  }
}

```

`1` is a massive footgun, but if you're expecting to be able to shoot your foot, arguably you should be allowed to. It might be enough to put a big warning in the documentation that wildcards are allowed, but discouraged.

I can have a go at making a PR for `1` if that's alright with you, `2` I think requires a bit more planning.

**Comment by smeijer** [comment]
Regarding 2) It might open the box, and I'm actually thinking that it might not be such a terrible idea to add support for "loaders" or "plugins". That would be the third option though, as the "assets" could then be implemented as a plugin. But that would require even more planning.

If you wanna take a stab at 1), please do. I've added you as a collaborator on the project, so you can now make your branches directly on the repo rather than your fork if you want. That should ease things with GitHub blocking workflows from being run.

**Comment by smeijer** [comment]
Should we also count the number of ignored imports, and add them to the printed statistics?  

```diff
   unresolved imports  : 2
   unused dependencies : 29
   unimported files    : 86
+  ignored imports     : n       
```

**Comment by villelahdenvuo** [comment]
Also having the issue with unresolved imports using webpack loaders:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/633524/179240154-dbe3631f-2cf6-4ab4-9a4f-60e1b9abb696.png">

**Comment by FutureKode** [comment]
@ksjogo Same here, did you find a fix for .svg?react imports?

**Comment by ksjogo** [comment]
@FutureKode Half. We just run with "--show-unused-files" on CI only. :/

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
