### ISSUE TITLE
Use this tool as part of eslint

### ISSUE THREAD

**Issue by Southclaws** [smeijer/unimported#65]
First of all, great tool! Thanks for building and maintaining it. I was surprised at how difficult this is in JS/TS compared to other languages.

Is there a way to use this as part of an existing eslint setup? As an eslint plugin? Would be super useful to keep all the linting under a single command/tool.

If not, seems not a whole lot of work to build it, I could give it a shot: https://eslint.org/docs/developer-guide/working-with-plugins

**Comment by smeijer** [comment]
Hi, thanks for the kind words.

Unimported can be run as part of a CI setup, and you could run `eslint && unimported` in a single command. But, it currently doesn't run as an eslint plugin.

I'm also not sure if that's possible, or if it even makes sense. Eslint checks your code base on a per file basis. It makes sense to run eslint on only the files that have been changed.

But unimported needs to check all files in your repo, and  scan your full source folder to know what to report. We can't run it on just a few files, because that doesn't give the information we need to determin which files are truly unused.

I'm unaware of any eslint plugin that has this same requirement. I'd love to be wrong on this though.
